### PR TITLE
Renames "The Project" to "Heyer Alerta"

### LINKED ISSUE #20: Update project name to Heyer Alerta
Update all place-holder names and project references to "Heyer Alerta"

### PR DESCRIPTION
**Pull request by goldenapples**
Updates placeholder text throughout the repo.

Fixes #20.

### CODE REVIEW

**Comment by goldenapples** [comment]
I'm not sure if this is the correct styling - was it "alert" or "alerta"? Anyhow, this updates the text inside the repo. If it looks right, feel free to merge it and we can rename the repo accordingly.

**Review by blujan — COMMENTED** [review]
Also need to update static/src/components/Header/index.js (line 104) and configure.py (line 90)

**Comment by goldenapples** [comment]
Thanks - I updated those two remaining spots where the placeholder name was being used. (I didn't rebuild the production assets, as that would cause merge conflicts at this point.)

**Review by blujan — APPROVED** [review]
Similarly ignored anything I saw in the static/dist folder. Looks good.

**Comment by goldenapples** [comment]
Great. I'll merge. If you want, feel free to rename the repo to match. (Once the origin's name is changed, we'll all have to update it locally; `git remote set-url origin git@github.com:PortlandAssembly/heyer.git` or whatever...)

**Pull request merged**
